#:schema node_modules/wrangler/config-schema.json
name = "cfworker-host-alive"
main = "src/index.js"
compatibility_date = "2025-01-09"

# Disable Preview URLs
preview_urls = false

# Cron Triggers
[triggers]
crons = ["1-58/3 * * * *"] # 1-58/3 * * * * = run every 3 minute (but start at 2nd minute of each hour)

# Workers Logs
[observability]
enabled = true
# Invocation logs are disabled
[observability.logs]
invocation_logs = false

# Environment variable bindings
 [vars]
 DISCONNECTION_THRESHOLD = "185"  # Depends on how often the CRON job runs
# PO_APPTOKEN = "PUSHOVER_APP_TOKEN"  # Ensure to set secrets with `npx wrangler secret put PO_APPTOKEN` after deployment
# PO_USERKEY = "PUSHOVER_USER_KEY"  # Ensure to set secrets with `npx wrangler secret put PO_USERKEY` after deployment

# Bind D1 database
[[d1_databases]]
binding = "MONITORED_HOSTS_DB"
database_name = "host-alive"
database_id = "YOUR_DATABASE_ID"
